apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentry-dev

resources:
  - ../../base

patches:
  - path: config-patch.yaml

configMapGenerator:
  - name: agentry-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - DEBUG=true
      - CORS_ORIGINS=https://dev.agentry.io,http://localhost:3000

replicas:
  - name: agentry-backend
    count: 1
