apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - ollama-deployment.yaml
  - ollama-service.yaml
  - lancedb-pvc.yaml
  - configmap.yaml
